package com.mmxin.mapper;

import com.mmxin.pojo.Authority;
import com.mmxin.pojo.UserAuthority;

import java.util.List;

public interface UserAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated
     */
    int insert(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated
     */
    int insertSelective(UserAuthority record);

}