server:
  port: 8080

spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://18.218.214.85:3306/WaitingForever?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
          username: root
          password: CloseToYou12$$
          #配置初始化大小/最小/最大
          initial-size: 2
          min-idle: 2
          max-active: 20
          timeout: 50000
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 6000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 3000
          validation-query: SELECT 1
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    thymeleaf:
      cache: false
      mode: HTML
      encoding: UTF-8
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
    aop:
      auto: true
    mail:
      default-encoding: utf-8
      host: smtp.163.com
      #账号
      username: dengyouforever@163.com
      #发送者的邮箱密码
      password: aini7758521
      #端口
      port: 465
      #协议
      protocol: smtp
      properties:
        mail:
          debug: true
          smtp:
            ssl.enable: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.mmxin.pojo  # 注意：对应实体类的路径

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

######################
####邮件发送配置######
######################
